"use client";

import { useState } from "react";
import { CalendarDays, Camera, CheckCircle2, HeartHandshake, HelpCircle, PackageCheck, PawPrint, Search, ShoppingBasket, Users, X } from "lucide-react";
import { useOperationsStore, type RsvpChoice } from "@/stores/operationsStore";

type Tab = "events" | "clubs" | "help";
const rsvpLabels: Array<[RsvpChoice, string]> = [["going", "Пойду"], ["maybe", "Возможно"], ["not_going", "Не пойду"]];
const noticeMeta = {
  help: { label: "Помощь соседу", icon: HelpCircle, tone: "bg-sky-100 text-sky-800" },
  lost: { label: "Потеряно / найдено", icon: Search, tone: "bg-amber-100 text-amber-900" },
  pet: { label: "Найдено животное", icon: PawPrint, tone: "bg-violet-100 text-violet-800" },
  group_buy: { label: "Совместная покупка", icon: ShoppingBasket, tone: "bg-emerald-100 text-emerald-800" },
};

export default function CommunityPage() {
  const { events, clubs, notices, rsvp, toggleClub, resolveNotice } = useOperationsStore();
  const [tab, setTab] = useState<Tab>("events");
  const [notice, setNotice] = useState("");

  return <div className="min-h-screen bg-[#f8f7f2] pb-10">
    <header className="border-b border-stone-200/80 px-4 py-6 sm:px-6"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-green-800">Соседи рядом</p><h1 className="mt-1 text-2xl font-black tracking-[-.035em] text-stone-950 sm:text-3xl">События и сообщество</h1><p className="mt-1 text-sm leading-6 text-stone-600">Встречи, клубы, взаимопомощь и совместные инициативы вашего дома.</p><div className="mt-5 grid grid-cols-3 gap-1 rounded-2xl bg-stone-200/70 p-1" role="tablist">{([{ id: "events", label: "События", icon: CalendarDays }, { id: "clubs", label: "Клубы", icon: Users }, { id: "help", label: "Рядом", icon: HeartHandshake }] as const).map(({ id, label, icon: Icon }) => <button key={id} role="tab" aria-selected={tab === id} onClick={() => setTab(id)} className={`flex min-h-11 items-center justify-center gap-2 rounded-xl text-xs font-extrabold transition ${tab === id ? "bg-white text-stone-950 shadow-sm" : "text-stone-500"}`}><Icon className="h-4 w-4" />{label}</button>)}</div></header>
    {notice && <div className="mx-4 mt-4 flex items-center justify-between rounded-2xl border border-emerald-200 bg-emerald-50 p-3 text-xs font-bold text-emerald-900 sm:mx-6"><span className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4" />{notice}</span><button onClick={() => setNotice("")} aria-label="Закрыть"><X className="h-4 w-4" /></button></div>}

    {tab === "events" && <main className="space-y-4 px-4 py-5 sm:px-6">{events.map((event, index) => { const full = event.going >= event.capacity; return <article key={event.id} className="reveal-up overflow-hidden rounded-[28px] border border-stone-200 bg-white" style={{ animationDelay: `${index * 60}ms` }}><div className="bg-gradient-to-br from-green-900 via-green-800 to-emerald-700 p-5 text-white"><div className="flex items-start justify-between gap-4"><div><p className="text-[11px] font-extrabold uppercase tracking-[.13em] text-emerald-200">{event.startsAt}</p><h2 className="mt-2 text-xl font-black tracking-tight">{event.title}</h2><p className="mt-2 text-xs leading-5 text-emerald-50/90">{event.description}</p></div><CalendarDays className="h-7 w-7 text-emerald-300" /></div><p className="mt-4 text-xs font-bold text-emerald-100">{event.location}</p></div><div className="p-4"><div className="flex items-center justify-between text-xs"><span className="font-extrabold text-stone-900">{event.going} участников</span><span className={`font-bold ${full ? "text-rose-700" : "text-stone-500"}`}>{full ? "Мест нет" : `осталось ${event.capacity - event.going}`}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-stone-100"><div className="h-full rounded-full bg-violet-600 transition-[width] duration-500" style={{ width: `${Math.min(100, event.going / event.capacity * 100)}%` }} /></div><div className="mt-4 grid grid-cols-3 gap-2">{rsvpLabels.map(([choice, label]) => <button key={choice} disabled={full && choice === "going" && event.userRsvp !== "going"} onClick={() => { void rsvp(event.id, choice); setNotice(`Ответ «${label}» сохранён`); }} className={`min-h-10 rounded-xl text-[11px] font-extrabold transition disabled:opacity-40 ${event.userRsvp === choice ? "bg-green-800 text-white" : "bg-stone-100 text-stone-700 hover:bg-stone-200"}`}>{label}</button>)}</div><div className="mt-4 flex items-center gap-2 border-t border-stone-100 pt-3 text-[11px] font-bold text-stone-500"><Camera className="h-4 w-4" />Фотоальбом · {event.albumCount ? `${event.albumCount} фото` : "откроется после события"}</div></div></article>; })}<section className="rounded-[24px] border border-violet-200 bg-violet-50 p-4"><p className="text-xs font-extrabold text-violet-900">Напоминания включены</p><p className="mt-1 text-xs leading-5 text-violet-700">Участники получат уведомление за день и за час до начала.</p></section></main>}

    {tab === "clubs" && <main className="grid gap-3 px-4 py-5 sm:grid-cols-2 sm:px-6">{clubs.map((club, index) => <article key={club.id} className="reveal-up rounded-[26px] border border-stone-200 bg-white p-5" style={{ animationDelay: `${index * 55}ms` }}><span className="grid h-12 w-12 place-items-center rounded-2xl bg-violet-100 text-violet-800"><Users className="h-5 w-5" /></span><h2 className="mt-4 text-base font-black text-stone-950">{club.name}</h2><p className="mt-1 text-xs leading-5 text-stone-600">{club.description}</p><p className="mt-3 text-[11px] font-bold text-stone-500">{club.members} участников · внутренний чат</p><button onClick={() => { void toggleClub(club.id); setNotice(club.joined ? "Вы вышли из клуба" : "Вы вступили в клуб"); }} className={`mt-4 min-h-11 w-full rounded-xl text-xs font-extrabold ${club.joined ? "bg-stone-100 text-stone-700" : "bg-green-800 text-white"}`}>{club.joined ? "Выйти" : "Вступить"}</button></article>)}</main>}

    {tab === "help" && <main className="space-y-3 px-4 py-5 sm:px-6">{notices.filter((item) => item.status === "active").map((item, index) => { const meta = noticeMeta[item.kind]; const Icon = meta.icon; return <article key={item.id} className="reveal-up flex items-start gap-3 rounded-[24px] border border-stone-200 bg-white p-4" style={{ animationDelay: `${index * 50}ms` }}><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-2xl ${meta.tone}`}><Icon className="h-5 w-5" /></span><div className="min-w-0 flex-1"><p className="text-[10px] font-extrabold uppercase tracking-[.1em] text-stone-400">{meta.label}</p><h2 className="mt-1 text-sm font-black text-stone-950">{item.title}</h2><p className="mt-1 text-xs leading-5 text-stone-600">{item.description}</p><button onClick={() => { void resolveNotice(item.id); setNotice("Отмечено как решённое"); }} className="mt-3 rounded-xl bg-stone-100 px-3 py-2 text-[11px] font-extrabold text-stone-700">Закрыть вопрос</button></div></article>; })}<section className="rounded-[24px] border border-stone-200 bg-white p-4"><div className="flex items-center gap-3"><PackageCheck className="h-5 w-5 text-green-800" /><div><p className="text-sm font-black">Опросы сообщества</p><p className="mt-1 text-xs text-stone-500">Создаются через «Создать запись» и не смешиваются с официальными голосованиями собственников.</p></div></div></section></main>}
  </div>;
}
