import type { UserAccount } from "@/types/app";
export const DEFAULT_ACCOUNTS: UserAccount[] = [
  {
    id: "user-1",
    fullName: "Мария Иванова",
    phone: "+7 (777) 234-56-78",
    email: "maria@housesm.kz",
    role: "resident",
    roleLabel: "Собственник (Дом 2)",
    buildingNumber: "2",
    entranceNumber: 1,
    apartmentNumber: "45",
    verified: true,
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80",
    bio: "Живу в ЖК с 2023 года. Люблю порядок и зеленый двор!",
  },
  {
    id: "user-2",
    fullName: "Алексей Петров",
    phone: "+7 (701) 444-55-66",
    email: "alex@housesm.kz",
    role: "resident",
    roleLabel: "Собственник (Дом 1)",
    buildingNumber: "1",
    entranceNumber: 2,
    apartmentNumber: "12",
    verified: true,
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80",
    bio: "Инициатор установки камер в подъезде 2.",
  },
  {
    id: "user-hoa",
    fullName: "ОСИ «Солнечный»",
    phone: "+7 (727) 123-45-67",
    email: "osi@housesm.kz",
    role: "hoa_official",
    roleLabel: "Председатель ОСИ",
    buildingNumber: "1",
    entranceNumber: 1,
    apartmentNumber: "Офис ОСИ",
    verified: true,
    avatarUrl: "https://images.unsplash.com/photo-1577495508048-b635879837f1?w=200&auto=format&fit=crop&q=80",
    bio: "Официальный орган управления жилым комплексом.",
  },
  {
    id: "user-master",
    fullName: "Олег Смирнов",
    phone: "+7 (775) 123-99-88",
    email: "oleg.electrician@housesm.kz",
    role: "service_provider",
    roleLabel: "Мастер-электрик ЖК",
    buildingNumber: "1",
    entranceNumber: 1,
    apartmentNumber: "3",
    verified: true,
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80",
    bio: "Электрика любой сложности в нашем ЖК. Опыт 10 лет.",
  },
  {
    id: "user-admin",
    fullName: "Администратор Сообщества",
    phone: "+7 (777) 000-11-22",
    email: "admin@housesm.kz",
    role: "admin",
    roleLabel: "Администратор ЖК",
    buildingNumber: "2",
    entranceNumber: 2,
    apartmentNumber: "100",
    verified: true,
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&auto=format&fit=crop&q=80",
    bio: "Модерация социальной сети и верификация жителей.",
  },
];
